### ISSUE TITLE
Sling loading wrecks?

### ISSUE THREAD

**Issue by georgebazil** [ampersand38/amp#3]
Hi, 

My unit plans to use sling load rigging for vehicle recovery, and while we can get the option to place the hooks, as soon as we hit complete the rigging sling disappears as if though we never did it. Cheers

**Comment by ampersand38** [comment]
https://youtu.be/9Vnhp-tyk-4
https://github.com/ampersand38/sling-load-rigging/commit/c2d34535465c070505e81d0f3be4f30cce4a3a8e
