### ISSUE TITLE
Over water bug.

### ISSUE THREAD

**Issue by JackMenta** [ampersand38/amp#4]
**Game version:** 2.04.147719
**CBA Version:** 3.15.1
**ACE3 Version:** 3.13.6

**Mods:**
```
- CBA_A3
- ACE
- ACEX
- ACRE2
- CUP Weapons
- CUP Units
- CUP Vehicles
- CUP Terrains - Core
- CUP Terrains - Maps
- RHSUSAF
- RHSAFRF
- RHSGREF
- RKSL Studios - Attachments v3.02
- Community Factions Project (CFP)
- MBG Buildings 3 (Arma2 Legacy)
- MBG Bulidings Killhouses (Arma3 Remaster)
- 3CB BAF Weapons
- 3CB BAF Vehicles
- c.o.s.
- USAF Mod - Main
- USAF Mod - Utility
- USS Nimitz
- Jbad
- //RG Custom Content Pack------\\
- \\Reality Gaming Essential Mods// These two packs are unit specific made content, if the content is needed I can provide that. But I don't believe it is neccesary. 
```

**Description:**
- We have tried testing a little bit on some supply crates usually used to ressupply squads. What we tested is that if you add rope to an object on any surface that seems to be a couple of meters above water. the object goes through the floor.

**Steps to reproduce:**
- Spawn in a ship, boat or bridge. Anything that has a platform at a considerable height above water.
- Put down a ammo crate.
- Try and attach rope.

**Where did the issue occur?**
- Dedicated Multiplayer server.
**Additional information:**
- We haven't tested it on singleplayer.
- What we concluded is that the object we are attaching rope too. Seem to go to position 0 over AGL even over water. Is there something to be done to reference it's own position. So if the ropes get attached 20meters above i.e. on a carrier for example. that it doesn't try to move down to the waterline.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
Not sure what you want me to add here since the bug doens't cause crashes ':D
- If possible at the time the bug is encountered, go to Options and select "ACE Debug To Clipboard", this will print extensive debug information to the RPT file and copy it to clipboard.

**Comment by pterolatypus** [comment]
Found the problem - the "apex fitting" is given its position in `createVehicle`, but this expects `PositionATL` - this means the fitting is created underwater, and when the ropes are attached the box seems to be teleported there (or rather, to within the rope's default length of 10m from that position)
